### ISSUE TITLE
Attach binaries/deb to their associated release?

### ISSUE THREAD

**Issue by thorsummoner** [fbriere/eawpatches-package#1]
Firstly, thank you for tagging your stable releases (so many folks ignore doing so), I came to this request following a link on https://help.ubuntu.com/community/Midi/SoftwareSynthesisHowTo#Installing_TiMidity.2B-.2B- which linkewd me to an old binary/deb package. I am okayish as compiling software for myself, but I really prefer to have the binaries when applicable. Would you be able to post the generated .deb files of the latest stable version to Github's releases? Their is the blog post about the releases feature here https://github.com/blog/1547-release-your-software I am not 100% certain that you can append a binary to an existing release (but I am 100% confident that you should be able too)

Lastly, I appologise for reporting this to the github issue tracker as its not really a code-issue as much as a release-policy request.

**Comment by fbriere** [comment]
On Sun, Dec 21, 2014 at 01:17:16AM -0800, thorsummoner wrote:

> I came to this request following a link on https://help.ubuntu.com/community/Midi/SoftwareSynthesisHowTo#Installing_TiMidity.2B-.2B- which linkewd me to an old binary/deb package.

Oh my!  This is an old link indeed.  :)

> Would you be able to post the generated .deb files of the latest stable version to Github's releases?

I wasn't aware of this feature; thanks for the tip!  I took the
opportunity to add a few changes I forgot to commit, and attached the
resulting binary package to the new v10 release.

Thanks!
